ral-facilities/inventory-management-system-api

inventory_management_system_api/core/exceptions.py, inventory_management_system_api/routers/v1/catalogue_category.py, inventory_management_system_api/routers/v1/catalogue_item.py, inventory_management_system_api/services/catalogue_category.py, test/e2e/test_catalogue_category.py, test/unit/services/test_catalogue_category.py
Added logic to the creation and updating of catalogue categories to make sure that duplicate catalogue item property names are not possible. The logic also ensures that not case specific names (e.g. Property A and property a) are also seen as duplicates
closes #123
=> Duplicate catalogue item properties #123

inventory_management_system_api/repositories/catalogue_category.py, inventory_management_system_api/repositories/manufacturer.py, inventory_management_system_api/repositories/system.py, test/unit/repositories/conftest.py, test/unit/repositories/test_catalogue_category.py, test/unit/repositories/test_catalogue_item.py, test/unit/repositories/test_manufacturer.py, test/unit/repositories/test_system.py, test/unit/services/test_catalogue_category.py
Refactored logic to use `find_one` for checking for children elements. This was done for catalogue categories, systems and manufacturers. 
(note this has been done for catalogue items in #147)
closes #91
=> Replace count documents with find one #91

inventory_management_system_api/core/exceptions.py, inventory_management_system_api/repositories/item.py, inventory_management_system_api/routers/v1/item.py, inventory_management_system_api/schemas/item.py, inventory_management_system_api/services/item.py, test/e2e/test_item.py, test/unit/repositories/test_item.py, test/unit/services/conftest.py, test/unit/services/test_catalogue_category.py, test/unit/services/test_item.py
Implemented api endpoint to be able to edit an item. Properties are handled and validated like in catalogue items, however you cannot edit the `catalogue_item_id`
Closes #13
=> edit item #13

inventory_management_system_api/services/item.py, test/e2e/test_item.py, test/unit/services/test_item.py
Preserves the order of properties defined in the catalogue item when creating/updating an item.
Closes #162
=> Preserve the order of properties when creating or updating items #162

inventory_management_system_api/models/catalogue_category.py, inventory_management_system_api/schemas/catalogue_category.py, inventory_management_system_api/services/utils.py, test/e2e/mock_schemas.py, test/e2e/test_catalogue_category.py, test/e2e/test_catalogue_item.py, test/e2e/test_item.py, test/unit/services/test_utils.py
Adds the ability to specify `allowed_values` for a catalogue item property at the category level that is used in validating during catalogue item/item create and update requests and can be used on the front end to produce a drop down list of available options.
Closes #159
=> Add allowed_values in catalogue category properties #159

inventory_management_system_api/repositories/catalogue_category.py, inventory_management_system_api/repositories/system.py, inventory_management_system_api/repositories/utils.py, inventory_management_system_api/routers/v1/catalogue_category.py, inventory_management_system_api/routers/v1/system.py, inventory_management_system_api/schemas/catalogue_category.py, inventory_management_system_api/services/utils.py, test/e2e/test_catalogue_category.py, test/e2e/test_system.py, test/unit/repositories/conftest.py, test/unit/repositories/test_catalogue_category.py, test/unit/repositories/test_system.py, test/unit/repositories/test_utils.py
Prevents moving a system/category to a child of itself.
Closes #129
=> Prevent moving a system/category to child of itself #129

inventory_management_system_api/repositories/catalogue_item.py, inventory_management_system_api/schemas/catalogue_item.py, inventory_management_system_api/services/catalogue_category.py, inventory_management_system_api/services/catalogue_item.py, test/e2e/test_catalogue_item.py, test/unit/repositories/test_catalogue_category.py, test/unit/repositories/test_catalogue_item.py, test/unit/services/test_catalogue_category.py, test/unit/services/test_catalogue_item.py
Allows everything except manufacturer_id and properties to be updated in a catalogue item while it has children. Handled in the same way as #98.
Closes #153
=> Allow catalogue items update with children #153

.github/dependabot.yml
This PR configures Dependabot to update the Docker images used in the Dockerfiles.
=> Configure Dependabot to update Dockerfile dependencies

.github/dependabot.yml, .github/workflows/.ci.yml, Dockerfile, Dockerfile.prod
This PR pins the Python docker images in the Dockerfiles to commit SHAs so that Dependabot can create PRs each time there is a change in the upstream base images that the Python image is set to use as new SHAs are generated on every upstream change. Unfortunately, Dependabot only updates the Python versions but not the OS versions and there is an open issue for this. This means that we will have to do the Alpine version updates manually for now. This PR also configures Dependabot to ignore Python major and minor versions so again we will have to do such Python upgrades manually when we are ready to do that.
Please note that I have pinned it to an older SHA to verify that Dependabot will create a PR.
=> Pin python docker images to SHA

inventory_management_system_api/repositories/catalogue_category.py, inventory_management_system_api/repositories/catalogue_item.py, inventory_management_system_api/repositories/item.py, inventory_management_system_api/repositories/manufacturer.py, inventory_management_system_api/repositories/system.py, inventory_management_system_api/repositories/unit.py, test/unit/repositories/test_catalogue_category.py, test/unit/repositories/test_catalogue_item.py, test/unit/repositories/test_item.py, test/unit/repositories/test_manufacturer.py, test/unit/repositories/test_system.py, test/unit/repositories/test_unit.py
I thought this may be the best approach for #239, but happy to discuss. With this we can reuse any and all repo methods, but pass in the session after the transaction has started. Also has potential of use in consistent sessions (not that we need them), as get requests that happen after edit can use the same session in the update methods for example.
Note: Also replaces a few `nonexistent` -> `non-existent`, and fixes a mistake in move check tests (it was still mocking as though it was for breadcrumbs and didn't check the aggregate function was called)
Would also want these changes for #231, #234.
Closes #239
=> Add session parameter to all repo methods #239

scripts/dev_cli.py
Make `db-generate` dump when `-d` or `--dump` is supplied rather than when they aren't. Also it only cleared the test database as I had forgotten to specify ims.
=> Fix bug in dev_cli script's db-generate command

inventory_management_system_api/models/catalogue_item.py, inventory_management_system_api/models/item.py, inventory_management_system_api/repositories/catalogue_category.py, inventory_management_system_api/repositories/catalogue_item.py, inventory_management_system_api/repositories/item.py, inventory_management_system_api/routers/v1/catalogue_category.py, inventory_management_system_api/schemas/catalogue_category.py, inventory_management_system_api/schemas/catalogue_item.py, inventory_management_system_api/services/catalogue_category.py, inventory_management_system_api/services/catalogue_category_property.py, inventory_management_system_api/services/item.py, inventory_management_system_api/services/utils.py, test/e2e/test_catalogue_category_property.py, test/unit/repositories/conftest.py, test/unit/repositories/mock_models.py, test/unit/repositories/test_catalogue_category.py, test/unit/repositories/test_catalogue_item.py, test/unit/repositories/test_item.py, test/unit/services/conftest.py, test/unit/services/test_catalogue_category_property.py, test/unit/services/test_utils.py
See #245.
This PR should be working with https://github.com/ral-facilities/inventory-management-system/pull/530.
- Renames `CatalogueItemPropertyPostRequestSchema` -> `CatalogueCategoryPostRequestPropertySchema` so the new endpoint can use `CatalogueItemPropertyPostRequestSchema` as it requires a slightly different schema. This new name also reflects its location slightly better, although it technically should be `CatalogueCategoryPostRequestCatalogueItemPropertySchema` under the existing naming scheme, but that is very long. Further changes e.g. to `catalogue_item_properties` are left to a future issue
- Should we also change the type of property values to `Union[str, int, bool]` rather than Any?
- As we need the ids of catalogue items to know which items to update we can either use …
=> Add POST property endpoint for catalogue categories #259

inventory_management_system_api/repositories/catalogue_category.py, inventory_management_system_api/repositories/catalogue_item.py, inventory_management_system_api/repositories/item.py, inventory_management_system_api/routers/v1/catalogue_category.py, inventory_management_system_api/schemas/catalogue_category.py, inventory_management_system_api/services/catalogue_category_property.py, test/e2e/test_catalogue_category.py, test/e2e/test_catalogue_category_property.py, test/unit/repositories/test_catalogue_category.py, test/unit/repositories/test_catalogue_item.py, test/unit/repositories/test_item.py, test/unit/services/test_catalogue_category_property.py
Adds a patch endpoint for properties at the catalogue category level at
`/v1/catalogue-categories/{catalogue_category_id}/properties/{catalogue_item_property_id}`.
Changes to name are propagated through catalogue items and items, an allowed values list is only allowed to add items not change its type, remove them or add them if they weren't already (matches current front end implementation). All `modified_time`'s of the modified entities are are also updated.
Should just be missing e2e tests now.
Closes #266
=> Add PATCH endpoint for /properties #266

inventory_management_system_api/schemas/catalogue_category.py, test/e2e/test_catalogue_category.py, test/e2e/test_catalogue_category_property.py
Checks for catalogue category post and patch, and the new properties post and patch. String values are converted to lower case first like the front end check so two values with different capitalisation are treated as duplicates.
Closes #272
=> Add check for duplicate values in an allowed_values list #272

Dockerfile.prod, README.md, docker-compose.yml, inventory_management_system_api/logging.example.ini
This PR fixes the issue reported in #277 so any custom images created using the prod Docker image from Harbor as the base image while being in a different working directory would not result in any issues now. It also addresses #278 so the default logging in the prod Docker image will be to the console.
```Dockerfile
FROM harbor.stfc.ac.uk/inventory-management-system/ims-api:pr-279
WORKDIR /inventory-management-system-api-run
USER root
RUN set -eux; \
\
mkdir logs; \
\
chown -R inventory-management-system-api:inventory-management-system-api logs/;
WORKDIR /inventory-management-system-api-run/inventory_management_system_api
COPY --chown=inventory-management-system-api:inventory-management-system-api logging.ini ./logging.ini
USER inventory-management-system-api
```
closes #277 
closes #278
=> Changes to production Docker image

Dockerfile, Dockerfile.prod
Bumps python from 3.12.3-alpine3.19 to 3.12.3-alpine3.20.
=> Bump python from 3.12.3-alpine3.19 to 3.12.3-alpine3.20

inventory_management_system_api/core/config.py, inventory_management_system_api/core/database.py, inventory_management_system_api/main.py
This PR changes the types of the `DatabaseConfig` Pydantic class fields from `str` to `SecretStr`. This means that they will be serialised to ``**********`` when accessing their values, or using `.model_dump()`, `.dict()`, or `.json()` (more info [here](https://docs.pydantic.dev/latest/examples/secrets/)). `get_secret_value()` should be used to access the secret value.
It also sets `hide_input_in_errors` on the models to `True` so that the input values can be hidden when `ValidationError` is raised during the validation.
=> Handling sensitive config values

.github/workflows/release-build.yml
See #321. We can probably use a caller workflow eventually so we can reuse it, but for now we will just copy and paste them.
Closes #321
=> Add Docker release-build workflow #321

.github/dependabot.yml
This PR configures Dependabot to maintain Dockerfile and GitHub Actions updates on, both, `develop` and `main`.
connect to #326
=> Configure Dependabot to do Docker image and GitHub Action updates on multiple branches

inventory_management_system_api/repositories/manufacturer.py, inventory_management_system_api/routers/v1/manufacturer.py, inventory_management_system_api/services/manufacturer.py, test/e2e/test_catalogue_item.py, test/e2e/test_manufacturer.py, test/mock_data.py, test/unit/repositories/test_manufacturer.py, test/unit/services/conftest.py, test/unit/services/test_manufacturer.py
Refactors the manufacturer tests in the same format as in #302 as part of #90.
Removed the tests:
- `test_partial_update_address` (repo unit and e2e) as the standard update is enough
- `test_get_with_non_existent_id` as not needed
closes #312
=> Refactor manufacturer tests

inventory_management_system_api/services/catalogue_category.py, test/mock_data.py, test/unit/repositories/test_catalogue_category.py, test/unit/repositories/test_system.py, test/unit/services/test_catalogue_category.py, test/unit/services/test_catalogue_category_property.py, test/unit/services/test_system.py
- Disabled pylint duplicate-code in all new unit test files - It frequently picked up the tests as they are now similar as the logic is abstracted into one place - I think this will be needed in the e2e test files later too
- Addresses some minor comments from Viktor while doing manufacturer tests
Removed the tests:
- `test_create_with_whitespace_name` didn't actually test removing whitespace - it doesn't
- `test_get_with_non_existent_id` - Right now the code just returns whatever comes from the repo, whether none or not, so I didn't think this test was necessary (systems doesn't have one either)
- `test_update_properties_to_have_duplicate_names` logic is in utils, which is tested elsewhere, function call is asserted instead
Add a set up instructions describing how the reviewer should …
=> Refactor CatalogueCategoryService unit tests #308

inventory_management_system_api/services/catalogue_item.py, test/e2e/test_catalogue_category.py, test/mock_data.py, test/unit/repositories/test_catalogue_category.py, test/unit/services/conftest.py, test/unit/services/test_catalogue_category.py, test/unit/services/test_catalogue_item.py
See #341.
- Removed some unit tests that were already handled by `utils.process_properties`  e.g. `test_update_add_non_mandatory_property`, `test_update_remove_non_mandatory_property` etc.
- Removed `test_get_with_non_existent_id` - Logic handled in repo unit tests and e2e tests (matches already refactored service tests)
- Found and fixed #349 
I think we should be able to clean up the mock_create/update methods later by adding some additional functions in the tests/helper functions in conftest, although its not clear how it will impact items yet or the e2e tests yet.
Closes #341, Closes #349
=> Refactor CatalogueItemService unit tests #341

inventory_management_system_api/repositories/item.py, test/e2e/test_catalogue_item.py, test/mock_data.py, test/unit/repositories/conftest.py, test/unit/repositories/test_catalogue_category.py, test/unit/repositories/test_catalogue_item.py, test/unit/repositories/test_item.py, test/unit/repositories/test_manufacturer.py, test/unit/repositories/test_system.py, test/unit/repositories/test_usage_status.py
See #345.
- I noticed we test the `system_id` existence in the create, but not in the update (we do that in the service layer) - we may want to change this later for consistency
- Removed `test_list_with_invalid_system_id_filter` none of the other repo tests do invalid id checks
- Removed `test_with_catalogue_item_id_filter_no_matching_results` and `test_list_with_system_id_filter_no_matching_results` and similar - they are instead tested at once in `test_list_with_system_id_and_catalogue_category_id_with_no_results`
Closes #345
=> Refactor ItemRepo unit tests #345

inventory_management_system_api/services/catalogue_item.py, inventory_management_system_api/services/item.py, test/mock_data.py, test/unit/repositories/test_item.py, test/unit/repositories/test_system.py, test/unit/services/conftest.py, test/unit/services/test_catalogue_category.py, test/unit/services/test_catalogue_item.py, test/unit/services/test_item.py
See #346.
- Removed `test_create_with_invalid_catalogue_category_id` and `test_update_with_invalid_usage_status` - we don't normally do invalid id checks in service tests.
- Removed `test_get_with_non_existent_id` - Already asserting return value, doesn't matter if its None or an item.
- Removed some update properties tests that were effectively testing `utils.process_properties` e.g. `test_update_change_property_value` - instead added test on the merging of properties instead and assert its called with the right parameters
- There are a few TODO's left that I have put where I pretty much copied things from catalogue items - we should be able to put them in a common place although its not clear to me how at the moment
Add a set up instructions describing how the reviewer should test the …
=> Refactor ItemService unit tests #346

pyproject.toml
Bumps the `cryptography` library to address https://github.com/ral-facilities/inventory-management-system-api/security/dependabot/4 on `main`.
=> Bump cryptography from 42.0.8 to 43.0.1

pyproject.toml
Resolves https://avd.aquasec.com/nvd/2024/cve-2024-47874/ by updating FastAPI which allows starlette to be updated. Tested locally with `ldap-jwt-auth`. As well as with `docker-ims`'s dev configuration.
=> Update FastAPI to v0.115

test/unit/services/test_usage_status.py
Found a typo in the usage status service test, identified [here](https://github.com/ral-facilities/object-storage-api/pull/61#issuecomment-2444542676). Checked other unit tests for a similar error, no other instance found.
=> Usage Status Service Test Fix

inventory_management_system_api/routers/v1/catalogue_category.py, inventory_management_system_api/routers/v1/catalogue_item.py, test/e2e/test_catalogue_category.py, test/e2e/test_catalogue_item.py
Edit the returned exception message to make it clearer when trying to update protected fields on a catalogue item or catalogue category that has a child element.
Resolves #353
=> Edit exception message when editing certain fields of a catalogue item with children

Dockerfile.prod
The `requirements.txt` file with all the production dependencies pinned was introduced as part of https://github.com/ral-facilities/inventory-management-system-api/pull/471 so I thought that there is no need to copy the `pyproject.toml` file and do `pip install .` anymore. However, it turns out the `ims-migrate` migration script needs to be installed so we still have to do this.
closes #483
=> Fix `ims-migrate` migration script in production Docker image

README.md
Updates the README to fix an incorrect replica set initialisation command that lead to #482. The host should have been localhost for this setup as host networking is being used. The dev_cli script already reflected this change as its default is to use localhost but the manual command was still using the container name left over from before host networking was being used.
Closes #482
=> Update incorrect replica set initialisation command in readme #482

.github/workflows/.ci.yml, .github/workflows/release-build.yml
Replicates Viktor's changes from scigateway-auth and object-storage-api to prevent us from pushing images each time the CI runs, and instead only when manually requested.
Also replicates the changes to the CI to allow dependabot PRs to pass as found in https://github.com/ral-facilities/object-storage-api/pull/131. I have not removed the previous secret as would require the same changes on main for it to still function.
Tested https://github.com/ral-facilities/inventory-management-system-api/actions/runs/14464604738.
Closes #171, Closes #494
=> Only push docker images when manually requested #443

inventory_management_system_api/core/exceptions.py, inventory_management_system_api/repositories/catalogue_item.py, inventory_management_system_api/routers/v1/catalogue_item.py, inventory_management_system_api/services/catalogue_item.py, test/e2e/test_catalogue_item.py, test/unit/repositories/test_catalogue_item.py, test/unit/services/test_catalogue_item.py
See #525. Prevents deletion of catalogue items that are assigned as the replacement of obsolete catalogue items.
Closes #525
=> Prevent deletion of catalogue items that are replacements for others #525

inventory_management_system_api/main.py, inventory_management_system_api/models/rule.py, inventory_management_system_api/models/system_type.py, inventory_management_system_api/repositories/catalogue_category.py, inventory_management_system_api/repositories/rule.py, inventory_management_system_api/repositories/system.py, inventory_management_system_api/repositories/utils.py, inventory_management_system_api/routers/v1/catalogue_category.py, inventory_management_system_api/routers/v1/rule.py, inventory_management_system_api/routers/v1/system.py, inventory_management_system_api/schemas/rule.py, inventory_management_system_api/schemas/system.py, inventory_management_system_api/services/rule.py, inventory_management_system_api/services/system.py, test/e2e/test_catalogue_category.py, test/e2e/test_catalogue_item.py, test/e2e/test_item.py, test/e2e/test_rules.py, test/e2e/test_system.py, test/e2e/test_usage_status.py, test/mock_data.py, test/unit/repositories/test_catalogue_category.py, test/unit/repositories/test_rule.py, test/unit/repositories/test_system.py, test/unit/repositories/test_utils.py, test/unit/services/conftest.py, test/unit/services/test_item.py, test/unit/services/test_rule.py, test/unit/services/test_system.py
Adds a `/rules` GET endpoint that returns a list of rules. The rules returned contain the full system type & usage status objects rather than just their IDs for ease of use. It also accepts filtering on the source and destination system types, with a value of `"null"` indicating they should have `null` as their ID (just like we do for `parent_id`'s). This is required so the front end can obtain a list of system types that are valid for creation, deletion and move operations.
- I noticed the usage status OUT models were using string `_id` values. Considering it is what is put into an Out model it should have been given as ObjectId's, so I fixed them.
Closes #544
=> Add rules list endpoint #544

inventory_management_system_api/repositories/rule.py, inventory_management_system_api/routers/v1/item.py, inventory_management_system_api/services/catalogue_item.py, inventory_management_system_api/services/item.py, test/e2e/test_catalogue_category_property.py, test/e2e/test_catalogue_item.py, test/e2e/test_item.py, test/e2e/test_setting.py, test/e2e/test_system.py, test/e2e/test_usage_status.py, test/mock_data.py, test/unit/repositories/test_catalogue_item.py, test/unit/repositories/test_item.py, test/unit/repositories/test_rule.py, test/unit/repositories/test_system.py, test/unit/repositories/test_usage_status.py, test/unit/services/conftest.py, test/unit/services/test_item.py, test/unit/services/test_system.py
This PR implements moving rules and modifies the item update behaviour so that a user:
- Cannot change usage status on its own
- Cannot change usage status when moving between systems of the same type
- Can only move the item between systems or change the usage status when satisfying a rule i.e. moving between systems of the same src and dst types and setting the usage status to be the same as in that rule
This functionality also technically works with multiple rules of the same src and dst system type's but different usage statuses, allowing the usage status to be chosen by the user (but the front end wont be implementing this, so its on the configuration/sysadmin to avoid duplicating them).
- I split up the system and usage status id update up into a new function much like systems has …
=> Implement moving rules #541

README.md, codecov.yml, inventory_management_system_api/cli/configure.py, inventory_management_system_api/cli/main.py, inventory_management_system_api/services/setting.py, pyproject.toml
Adds a CLI `ims` for setting the spares definition. See updated readme for instructions on how to use.
- No specific validation is done on the user inputs, if you enter something in the wrong format it will just give an error (in colour thanks to `rich`)
- This is an interactive command requiring user input - this seemed the easier option for our current use case. The alternative is using parameters in the command such as the codes/ids, but that seemed more complicated to use, likely requiring extensive usage of the `--help` and additional commands to look up what currently exists. It also misses out on having explanations and warning messages.
- I have told codecov to ignore coverage for the CLI as unit tests are difficult to implement for this case.
- You can use `ims …
=> Add sysadmin CLI with command to set spares definition #595
